# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
ja:
 languageCode: ja
 contentDir: content/ja
 title: 西原 慧 のホームページ
 params:
   description: 研究や趣味についてのメモ書き
 menu:
   main:
    - name: Demo
      url: '#about'
      weight: 10
    - name: Posts
      url: '#posts'
      weight: 20
    - name: Projects
      url: '#projects'
      weight: 30
    - name: Talks
      url: '#talks'
      weight: 40
    - name: Publications
      url: '#featured'
      weight: 50
    - name: Courses
      url: courses/
      weight: 60
    - name: Contact
      url: '#contact'
      weight: 70